server {
    listen 80;
    server_name gulrot.net;

    root /usr/share/nginx/html; # Or your static file path
    index index.html;

    # Rewrite rule to remove .html extension
    rewrite ^(/.*)\.html(\?.*)?$ $1$2 permanent;

    # Try files with and without .html extension, and as a directory
    try_files $uri $uri.html $uri/ =404;
}